Blacksmoke16/oq

README.md, shard.yml, snap/snapcraft.yaml, spec/oq_spec.cr, spec/spec_helper.cr, spec/to_xml_spec.cr, src/oq.cr, src/oq_cli.cr, src/to_xml.cr
=> Release `0.1.0`

spec/oq_spec.cr, spec/to_xml_spec.cr, src/to_xml.cr
=> Makes null/nil values be self closing tags in XML

spec/converters/yaml_spec.cr, src/converters/yaml.cr
=> Revert Yaml.deserialize to allow for anchors/alises

spec/converters/yaml_spec.cr, spec/oq_spec.cr, spec/spec_helper.cr, src/oq.cr
Make yaml spec failures less flakey
Fixes #25 
Fixes #24
=> Set correct exit code on jq failure

shard.yml, snap/snapcraft.yaml, src/converters/xml.cr, src/converters/yaml.cr, src/oq.cr
=> Migrate json.kind to use enums

README.md, shard.yml, snap/snapcraft.yaml, src/oq.cr
* Resolves issue with data being cut off on MacOS
* XML deserialization support
=> Release 1.0.0

.github/workflows/deployment.yml
Enables checkout@v2 support so :crossed_fingers:
=> update pages deploy action again

LICENSE, README.md, shard.yml, spec/converters/xml_spec.cr, src/converters/xml.cr, src/converters/yaml.cr, src/oq_cli.cr
* Support wrapping data in CDATA if key is prefixed with !
* Fix some 0.34.0 warnings
=> Support wrapping XML value in CDATA

.github/workflows/deployment.yml, README.md, shard.yml, snap/snapcraft.yaml, src/oq.cr
* Bumps versions to `1.1.1`
* Updates Ameba to `0.13.x`
=> Release 1.1.1

spec/converters/yaml_spec.cr
* Should help prevent failures depending on the libyaml version
=> Update some YAML serialization specs to be less strict

README.md
The URL for downloading needed to be fixed (was missing a "v"). The `curl` line is because I was using `curl`, and the lack of `-L` bit me. If you like I can throw out the `curl` line.
Thanks for a clean lib that doesn't make demands on my environment!
=> Fix download URL in Docker example

shard.yml, spec/assets/data2.yml, spec/oq_spec.cr, src/oq.cr
Fixes #70
I'll wait to hear your thoughts @blurayne before merging.
=> Convert each non JSON input file individually

README.md, spec/assets/stream-data.json, spec/oq_spec.cr, spec/processor_spec.cr, src/oq.cr, src/oq_cli.cr
* Allow providing custom arrays/IOs to use for processing
* Defaults to CLI related types
* Create an actual initializer and add setters to make the lib API better
=> Support using `oq` as a lib

README.md, shard.yml, snap/snapcraft.yaml, spec/oq_spec.cr, src/oq.cr
* Fix bug when (json)arg name references a dir/file
* Simplify some specs that don't require input
* Bump versions
Fixes #78
=> Allow for file/directory (json)arg references

.github/workflows/deployment.yml
Fixes https://github.com/Blacksmoke16/oq/runs/2948360597?check_suite_focus=true
=> Install `yaml-static` in deployment container

.github/workflows/deployment.yml, snap/snapcraft.yaml
* Enable Full RELRO on built binary & snap builds
* Move snap releases into GHA
* Add some extra metadata to the snap config
Fixes #81
=> Snap & Build improvements

src/converters/xml.cr, src/oq.cr
* Deprecate non query variants
* Can remove them in oq `2.0`
=> Make Bool getters query methods

.github/workflows/deployment.yml
* Add name properties to snap job
=> Add deployment job for homebrew

.github/workflows/deployment.yml
Tested this out via https://github.com/Blacksmoke16/testing/runs/4064021679?check_suite_focus=true, and it worked good. :shipit:.
=> Update doc deployment job

README.md, shard.yml, snap/snapcraft.yaml, spec/oq_spec.cr, spec/spec_helper.cr, src/oq.cr, src/oq_cli.cr
Resolves https://github.com/Blacksmoke16/oq/issues/101
=> Use empty IO on `null` input

README.md, shard.yml, snap/snapcraft.yaml, spec/assets/test.jq, spec/oq_spec.cr, spec/spec_helper.cr, src/oq.cr
=> Handle optional space in `-L` option

shard.yml
* Bump min Crystal version to `~> 1.4`
Fixes the CI failure
=> Bump `ameba` to `~> 1.0`

.github/workflows/ci.yml, .github/workflows/deployment.yml, shard.yml, src/converters/xml.cr
- Bump GHA action versions to resolve node deprecation
=> Fix ameba issue and pin the version

.github/workflows/ci.yml
Should help work around https://github.com/crystal-ameba/ameba/issues/354
=> Leverage the non alpine version for ameba

shard.yml, src/converters/xml.cr, src/oq.cr
=> Bump `ameba` to `1.5.0`

spec/oq_spec.cr, spec/processor_spec.cr
May need to do some more follow ups to account for new features/changes as well.
https://github.com/jqlang/jq/releases/tag/jq-1.7
=> Make specs compatible with jq 1.7
